name: FE Tests

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  fe-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright FE tests
        run: npx playwright test tests/fe

      - name: Upload FE Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fe-report-${{ matrix.os }}
          path: playwright-report/
